// Code generated by protoc-gen-go.
// source: cache.proto
// DO NOT EDIT!

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	cache.proto

It has these top-level messages:
	Data
*/
package model

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Data struct {
	Raw        string `protobuf:"bytes,1,opt,name=raw" json:"raw,omitempty"`
	ModifyTime int64  `protobuf:"varint,2,opt,name=modify_time" json:"modify_time,omitempty"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
