// Code generated by protoc-gen-go.
// source: cache.proto
// DO NOT EDIT!

/*
Package levelcache is a generated protocol buffer package.

It is generated from these files:
	cache.proto

It has these top-level messages:
	Data
*/
package levelcache

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type CompressionType int32

const (
	CompressionType_None   CompressionType = 0
	CompressionType_Snappy CompressionType = 1
)

var CompressionType_name = map[int32]string{
	0: "None",
	1: "Snappy",
}
var CompressionType_value = map[string]int32{
	"None":   0,
	"Snappy": 1,
}

func (x CompressionType) String() string {
	return proto.EnumName(CompressionType_name, int32(x))
}

type Data struct {
	Raw             []byte          `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	ModifyTime      int64           `protobuf:"varint,2,opt,name=modify_time" json:"modify_time,omitempty"`
	CompressionType CompressionType `protobuf:"varint,3,opt,name=compression_type,enum=levelcache.CompressionType" json:"compression_type,omitempty"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("levelcache.CompressionType", CompressionType_name, CompressionType_value)
}
